# üìò Pre-entrega

**Nombre del alumno:** Gonzalo Gomez Outon (Falta completar finn de semana)
__________________________

## üß© Etapa 1: Recopilaci√≥n y Preparaci√≥n de Datos
**Objetivo:** Demostrar habilidades en Python, familiaridad con el entorno de trabajo y conocimientos b√°sicos sobre manipulaci√≥n de datos.

### 1Ô∏è‚É£ Carga de datos

In [ ]:
# TODO: Cargar los datasets como DataFrames usando pandas.
# Sugerencia: utilizar pd.read_csv() para cargar los archivos CSV.
# Record√° verificar la ruta correcta y revisar las primeras filas con .head().
import pandas as pd
import numpy as np

In [ ]:
# Montar la unidad
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
# Verificar que los archivos csv se encuentren en la carpeta datasets
import os
os.listdir("/content/drive/MyDrive/datasets")

['clientes.csv', 'marketing.csv', 'ventas.xlsx', 'ventas.csv']

In [17]:
# Definimos las rutas de los datasets.
# En Google Colab, si sub√≠s archivos, pod√©s usar la carpeta /content o montar Drive.
# Aqu√≠ dejamos rutas relativas para que sea f√°cil reemplazarlas si cambia la ubicaci√≥n.
ruta_ventas = "/content/drive/MyDrive/datasets/ventas.csv"
ruta_clientes = "/content/drive/MyDrive/datasets/clientes.csv"
ruta_marketing = "/content/drive/MyDrive/datasets/marketing.csv"

# Cargamos los CSV como DataFrames.
ventas = pd.read_csv(ruta_ventas)
clientes = pd.read_csv(ruta_clientes)
marketing = pd.read_csv(ruta_marketing)

# Validamos formas para comprobar que se cargaron correctamente.
print("ventas.shape ->", ventas.shape)
print("clientes.shape ->", clientes.shape)
print("marketing.shape ->", marketing.shape)

# Mostramos las primeras filas de cada dataset para corroborar estructura de columnas.
display(ventas.head(5))
display(clientes.head(5))
display(marketing.head(5))

ventas.shape -> (3035, 6)
clientes.shape -> (567, 5)
marketing.shape -> (90, 6)

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoraci√≥n
1,811,L√°mpara de mesa,$105.10,5.0,02/01/2024,Decoraci√≥n
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodom√©sticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodom√©sticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodom√©sticos

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bah√≠a Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  L√°mpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

###**Script b√°sico que calcule las ventas mensuales usando variables y operadores**

In [66]:
#Ejemplo inventado#
ventasenero = 250000
ventasfebrero = 19000
ventasmarzo = 500000

#Calculo total trimestral
total_trimestre = ventasenero + ventasfebrero + ventasmarzo

#Promedio mensual
promediomensual = total_trimestre/3

print("Ventas Mensuales (Python b√°sico)")
print("Enero:",ventasenero)
print("Febrero:",ventasfebrero)
print("Marzo:",ventasmarzo)
print("Total Trimestre:", total_trimestre)
print("Promedio Mensual:", promedio_mensual)

Ventas Mensuales (Python b√°sico)
Enero: 250000
Febrero: 19000
Marzo: 500000
Total Trimestre: 769000
Promedio Mensual: 181666.66666666666

### 2Ô∏è‚É£ An√°lisis exploratorio inicial

In [53]:
# TODO: Realizar un an√°lisis exploratorio inicial de los DataFrames.
# Sugerencia: usar m√©todos como .info(), .describe(), .shape y .columns. dtypes.
# Esto te ayudar√° a entender la estructura y el contenido de los datos.
# Pod√©s incluir comentarios sobre observaciones iniciales.
print("An√°lisis exploratorio de Clientes:")

print("\nPrimeras filas Clientes:")
print(clientes.head())

print("\n√öltimas filas:")
print(clientes.tail())

print("\nDimensiones (filas, columnas):", clientes.shape)

print("\nInformaci√≥n del DataFrame:")
print(clientes.info())

print("\nEstad√≠sticas descriptivas:")
print(clientes.describe())


print("An√°lisis exploratorio de Ventas:")

print("\nPrimeras filas Ventas:")
print(ventas.head())

print("\n√öltimas filas:")
print(ventas.tail())

print("\nDimensiones (filas, columnas):", ventas.shape)

print("\nInformaci√≥n del DataFrame:")
print(ventas.info())

print("\nEstad√≠sticas descriptivas:")
print(ventas.describe())


print("An√°lisis exploratorio de Marketing:")

print("\nPrimeras filas Marketing:")
print(marketing.head())

print("\n√öltimas filas:")
print(marketing.tail())

print("\nDimensiones (filas, columnas):", marketing.shape)

print("\nInformaci√≥n del DataFrame:")
print(marketing.info())

print("\nEstad√≠sticas descriptivas:")
print(marketing.describe())

An√°lisis exploratorio de Clientes:

Primeras filas Clientes:
   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bah√≠a Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

√öltimas filas:
     id_cliente           nombre  edad       ciudad  ingresos
562         563    Dione Forsyde    29      Posadas  26757.73
563         564      Fleming Gow    39     Santa Fe  43674.96
564         565  Jewelle Mabbett    33      C√≥rdoba  30522.64
565         566      Lauri Munns    23  Resistencia  31259.14
566         567      Micah Matis    31   Corrientes  42927.86

Dimensiones (filas, columnas): (567, 5)

Informaci√≥n del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  567 non-null    int64
 1   nombre      567 non-null    object
 2   edad        567 non-null    int64
 3   ciudad      567 non-null    object
 4   ingresos    567 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 22.3+ KB
None

Estad√≠sticas descriptivas:
       id_cliente        edad      ingresos
count  567.000000  567.000000    567.000000
mean   284.000000   37.940035  34668.739012
std    163.823075   10.202885  12974.531446
min      1.000000   20.000000    170.290000
25%    142.500000   30.000000  26015.240000
50%    284.000000   37.000000  35066.830000
75%    425.500000   43.000000  42457.100000
max    567.000000   81.000000  88053.010000
An√°lisis exploratorio de Ventas:

Primeras filas Ventas:
   id_venta           producto   precio  cantidad fecha_venta  \
0       792  Cuadro decorativo   $69.94       5.0  02/01/2024
1       811    L√°mpara de mesa  $105.10       5.0  02/01/2024
2      1156           Secadora   $97.96       3.0  02/01/2024
3      1372           Heladera  $114.35       8.0  02/01/2024
4      1546           Secadora  $106.21       4.0  02/01/2024

           categoria
0         Decoraci√≥n
1         Decoraci√≥n
2  Electrodom√©sticos
3  Electrodom√©sticos
4  Electrodom√©sticos

√öltimas filas:
      id_venta                producto   precio  cantidad fecha_venta  \
3030      1837         Horno el√©ctrico  $104.12       9.0  30/12/2024
3031      2276                  Laptop   $85.27       9.0  30/12/2024
3032      2696                  Laptop  $107.81       4.0  30/12/2024
3033      2913              Smartphone   $99.85       7.0  30/12/2024
3034      2930  Consola de videojuegos   $55.47       6.0  30/12/2024

              categoria
3030  Electrodom√©sticos
3031        Electr√≥nica
3032        Electr√≥nica
3033        Electr√≥nica
3034        Electr√≥nica

Dimensiones (filas, columnas): (3035, 6)

Informaci√≥n del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_venta     3035 non-null   int64
 1   producto     3035 non-null   object
 2   precio       3033 non-null   object
 3   cantidad     3033 non-null   float64
 4   fecha_venta  3035 non-null   object
 5   categoria    3035 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 142.4+ KB
None

Estad√≠sticas descriptivas:
          id_venta     cantidad
count  3035.000000  3033.000000
mean   1499.851400     6.496538
std     866.465379     3.457250
min       1.000000     1.000000
25%     748.500000     3.000000
50%    1502.000000     7.000000
75%    2249.500000     9.000000
max    3000.000000    12.000000
An√°lisis exploratorio de Marketing:

Primeras filas Marketing:
   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  L√°mpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

√öltimas filas:
    id_campanha            producto  canal  costo fecha_inicio   fecha_fin
85           70          Aspiradora     TV   3.06   13/12/2024  29/12/2024
86           89           Televisor     TV   4.98   13/12/2024    8/2/2025
87           68   Rinc√≥n de plantas     TV   5.81   17/12/2024   14/2/2025
88           33            Secadora  Email   3.80   20/12/2024    7/1/2025
89           11  Freidora el√©ctrica   RRSS   5.27   29/12/2024   21/1/2025

Dimensiones (filas, columnas): (90, 6)

Informaci√≥n del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_campanha   90 non-null     int64
 1   producto      90 non-null     object
 2   canal         90 non-null     object
 3   costo         90 non-null     float64
 4   fecha_inicio  90 non-null     object
 5   fecha_fin     90 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.3+ KB
None

Estad√≠sticas descriptivas:
       id_campanha      costo
count    90.000000  90.000000
mean     45.500000   4.928667
std      26.124701   0.947750
min       1.000000   2.950000
25%      23.250000   4.372500
50%      45.500000   4.900000
75%      67.750000   5.562500
max      90.000000   7.390000

### 3Ô∏è‚É£ Calidad de los datos

In [ ]:
# TODO: Identificar valores nulos y duplicados en los conjuntos de datos.
# Sugerencia: usar .isna().sum() y .duplicated().sum().
# Documentar las observaciones con print() o comentarios.

## üßπ Etapa 2: Preprocesamiento y Limpieza de Datos
**Objetivo:** Demostrar conocimiento de las t√©cnicas de limpieza y transformaci√≥n de datos.

### 4Ô∏è‚É£ Limpieza de datos

In [95]:
# TODO: Limpiar el conjunto de datos eliminando duplicados y caracteres no deseados.
# Sugerencia: aplicar .drop_duplicates(), .str.strip(), .str.replace() seg√∫n el caso.
# Documentar el proceso y los resultados.
# Eliminar nulos
print("DataFrame sin nulos:")
print(clientes.dropna())

# Rellenar nulos
print("\nRelleno de nulos con 0:")
print(clientes.fillna(0))

# Renombrar columnas
clientes_ren = clientes.rename(columns={"nombre": "NombreCliente"})
print("\nRenombrado de columna Cliente:")
print(clientes_ren.head())

# Eliminar columna
print("\nSin columna Edad:")
print(clientes.drop("edad", axis=1).head())

# Eliminar duplicados
print("\nEliminar duplicados:")
print(df.drop_duplicates())

DataFrame sin nulos:
     id_cliente               nombre  edad         ciudad  ingresos
0             1      Aloysia Screase    44  Mar del Plata  42294.68
1             2  Kristina Scaplehorn    25        Posadas  24735.04
2             3       Filip Castagne    50    Resistencia  35744.85
3             4          Liuka Luard    39   Bah√≠a Blanca  27647.96
4             5        Dore Cockshtt    28        Rosario  28245.65
..          ...                  ...   ...            ...       ...
562         563        Dione Forsyde    29        Posadas  26757.73
563         564          Fleming Gow    39       Santa Fe  43674.96
564         565      Jewelle Mabbett    33        C√≥rdoba  30522.64
565         566          Lauri Munns    23    Resistencia  31259.14
566         567          Micah Matis    31     Corrientes  42927.86

[567 rows x 5 columns]

Relleno de nulos con 0:
     id_cliente               nombre  edad         ciudad  ingresos
0             1      Aloysia Screase    44  Mar del Plata  42294.68
1             2  Kristina Scaplehorn    25        Posadas  24735.04
2             3       Filip Castagne    50    Resistencia  35744.85
3             4          Liuka Luard    39   Bah√≠a Blanca  27647.96
4             5        Dore Cockshtt    28        Rosario  28245.65
..          ...                  ...   ...            ...       ...
562         563        Dione Forsyde    29        Posadas  26757.73
563         564          Fleming Gow    39       Santa Fe  43674.96
564         565      Jewelle Mabbett    33        C√≥rdoba  30522.64
565         566          Lauri Munns    23    Resistencia  31259.14
566         567          Micah Matis    31     Corrientes  42927.86

[567 rows x 5 columns]

Renombrado de columna Cliente:
   id_cliente        NombreCliente  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bah√≠a Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

Sin columna Edad:
   id_cliente               nombre         ciudad  ingresos
0           1      Aloysia Screase  Mar del Plata  42294.68
1           2  Kristina Scaplehorn        Posadas  24735.04
2           3       Filip Castagne    Resistencia  35744.85
3           4          Liuka Luard   Bah√≠a Blanca  27647.96
4           5        Dore Cockshtt        Rosario  28245.65

Eliminar duplicados:

NameError: name 'df' is not defined

### 5Ô∏è‚É£ Transformaci√≥n de datos

In [97]:
# TODO: Aplicar filtros y transformaciones para crear una tabla de ventas
# que muestre solo los productos con alto rendimiento. calcular el percentil 80
# y filtrar los productos que superen ese umbral en ventas.
#quantile(0.8)
# Sugerencia: usar .query() o condiciones con operadores l√≥gicos.
# Seleccionar columna
print("Columna Cliente:")
print(clientes["nombre"])

# Varias columnas
print("\nCliente y Producto:")
print(clientes[["id_cliente", "nombre"]])

# Selecci√≥n con loc
print("\nValor con loc:")
print(df.loc[0, "Producto"])

# Selecci√≥n con iloc
print("\nValor con iloc:")
print(df.iloc[1, 2])

# Filtro con query
print("\nVentas con cantidad mayor a 2:")
print(df.query("Cantidad > 2"))

# Ordenar por Cantidad
print("Ordenado por Cantidad:")
print(df.sort_values("Cantidad"))

# Agrupar por Cliente
print("\nVentas agrupadas por cliente:")
print(df.groupby("Cliente")["Cantidad"].sum())

# Contar valores de producto
print("\nConteo de productos:")
print(df["Producto"].value_counts())

# Apply
print("\nPrecio con IVA (21%):")
print(df["Precio"].apply(lambda x: x * 1.21))

# Map
print("\nCliente en may√∫sculas:")
print(df["Cliente"].map(str.upper))

Columna Cliente:
0          Aloysia Screase
1      Kristina Scaplehorn
2           Filip Castagne
3              Liuka Luard
4            Dore Cockshtt
              ...
562          Dione Forsyde
563            Fleming Gow
564        Jewelle Mabbett
565            Lauri Munns
566            Micah Matis
Name: nombre, Length: 567, dtype: object

Cliente y Producto:
     id_cliente               nombre
0             1      Aloysia Screase
1             2  Kristina Scaplehorn
2             3       Filip Castagne
3             4          Liuka Luard
4             5        Dore Cockshtt
..          ...                  ...
562         563        Dione Forsyde
563         564          Fleming Gow
564         565      Jewelle Mabbett
565         566          Lauri Munns
566         567          Micah Matis

[567 rows x 2 columns]

Valor con loc:

NameError: name 'df' is not defined

### 6Ô∏è‚É£ Agregaci√≥n

In [ ]:
# TODO: Resumir las ventas por categor√≠a de producto y analizar los ingresos generados.
# Sugerencia: usar .groupby() y .agg() para generar m√©tricas como suma y promedio.

### 7Ô∏è‚É£ Integraci√≥n de datos, opcional, NO OBLIGATORIO

In [ ]:
# TODO: Combinar los sets de datos de ventas y marketing para obtener una visi√≥n m√°s amplia de las tendencias.
# Sugerencia: usar pd.merge() especificando la clave com√∫n entre ambos DataFrames.
# Documentar cualquier observaci√≥n relevante sobre la combinaci√≥n de datos.